language: rust
rust:
    - stable
    - nightly
cache: cargo
# Dependencies of kcov, used by coverage
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

sudo: required  # https://github.com/travis-ci/travis-ci/issues/9061

before_script:
  - cargo install --force cargo-travis
  - export PATH=$HOME/.cargo/bin:$PATH

script:
  - cargo test

after_success:
  - cargo coveralls